### ISSUE TITLE
Error in cerebellum command with ccfv2 annotation

### ISSUE THREAD

**Issue by lecriste** [BlueBrain/atlas-direction-vectors#16]
When running
`atlas-direction-vectors direction-vectors cerebellum`
with the ccfv2 annotation, I get this error:
```
File "/gpfs/bbp.cscs.ch/home/lcristel/BBP/atlas_pipelines/atlas-direction-vectors/atlas_direction_vectors/algorithms/layer_based_direction_vectors.py", line 289, in compute_layered_region_direction_vectors
    raise AtlasDirectionVectorsError(
atlas_direction_vectors.exceptions.AtlasDirectionVectorsError: Layer region ids were not correctly assigned from the layer_queries
Layered region ids: [0 1 3 4]
layer queries: ['SIMmo', 'SIMpu', 'SIMgr', 'cbf']
```
Instead, the isocortex command works with both the ccfv2 and ccfv3 annotation.
Is this expected?
If yes, shall we mention in the README that the `cerebellum` command is to be run with only a ccfv3 annotation?

**Comment by lecriste** [comment]
@drodarie, I did use the combined ccfv2 annotation. Does it work for you?

**Comment by drodarie** [comment]
My apologies, I tested this code with an annotation atlas which has the Purkinje layer.
A simple fix will be to adapt or remove the test condition regarding the length of queries, in layer_based_direction_vectors.py line 288:
```
    if len(ids[ids != 0]) > len(layer_queries):
        raise AtlasDirectionVectorsError(
            f"Layer region ids cannot be assigned from the layer_queries\n"
            f"Layered region ids: {ids}\n"
            f"layer queries: {layer_queries}"
```
I will create a pull request so we can discuss this implementation.
